apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sut

resources:
  - namespace.yaml
  - postgres-main
  - postgres-auth
  - redis
  - auth-service
  - backend
  - frontend
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: mini-ecommerce
