apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-reporter

resources:
  - namespace.yaml
  - postgres
  - server
  - dashboard
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: test-reporter
