apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: sut
data:
  database_url: "postgresql://postgres:postgres@postgres-main:5432/ecommerce"
  redis_url: "redis://redis:6379"
  auth_service_url: "http://auth-service:8001"
