apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: sut
type: Opaque
stringData:
  secret_key: "k8s-secret-key-change-in-production"
  database_url: "postgresql://postgres:postgres@postgres-main:5432/ecommerce"
