apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: sut
data:
  # These URLs are accessed from the browser, so they must be the Ingress URLs
  # Overridden in overlays for different environments
  api_url: "http://localhost:8080/api"
  auth_url: "http://localhost:8080/auth"
