apiVersion: v1
kind: Service
metadata:
  name: postgres-main
  namespace: sut
spec:
  selector:
    app: postgres-main
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  # Headless service for StatefulSet
